# Generated by Django 4.1 on 2022-08-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_retal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
